name: reading-app

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:16-alpine
    container_name: reading-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reading_app
      TZ: Asia/Shanghai
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reading-app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: reading-app-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - reading-app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  reading-app-network:
    driver: bridge
